import assert from 'node:assert/strict';
import { test } from 'node:test';

import type {
  Action,
  ConditionMatch,
  ConditionNode,
  Rule,
  SieveModel,
} from '../model/types.js';
import { requiredExtensions } from './extensions.js';
import { generate } from './generate.js';
import { compileSieve, hasSievec } from './sievec.js';

const sievecSkip = hasSievec() ? false : 'sievec not installed (apt install dovecot-sieve)';

interface RuleSpec {
  id?: string;
  name?: string;
  enabled?: boolean;
  match?: ConditionMatch;
  negate?: boolean;
  /** Root-group children (tests and/or sub-groups). */
  tests?: ConditionNode[];
  actions?: Action[];
}

function rule(spec: RuleSpec): Rule {
  return {
    id: spec.id ?? 'r1',
    name: spec.name ?? 'Rule',
    enabled: spec.enabled ?? true,
    root: {
      type: 'group',
      match: spec.match ?? 'all',
      children: spec.tests ?? [],
      ...(spec.negate ? { negate: true } : {}),
    },
    actions: spec.actions ?? [],
  };
}

test('generates the canonical newsletter rule exactly', () => {
  const model: SieveModel = {
    rules: [
      rule({
        name: 'Newsletters',
        tests: [
          { type: 'header', fields: ['From'], match: 'contains', values: ['news@'] },
          { type: 'header', fields: ['Subject'], match: 'matches', values: ['*sale*'] },
        ],
        actions: [
          { type: 'fileinto', mailbox: 'INBOX/News' },
          { type: 'stop' },
        ],
      }),
    ],
  };

  const expected = [
    '# Generated by sieve-builder. The "# rule:[...]" comments enable round-trip',
    '# editing — keep them if you edit this script by hand.',
    '',
    'require "fileinto";',
    '',
    '# rule:[Newsletters]',
    'if allof(header :contains "From" "news@", header :matches "Subject" "*sale*")',
    '{',
    '\tfileinto "INBOX/News";',
    '\tstop;',
    '}',
    '',
  ].join('\n');

  assert.equal(generate(model), expected);
});

test('a single test omits allof/anyof', () => {
  const out = generate({
    rules: [rule({ tests: [{ type: 'size', over: true, limit: 1048576 }], actions: [{ type: 'discard' }] })],
  });
  assert.match(out, /if size :over 1048576\n/);
  assert.doesNotMatch(out, /allof|anyof/);
});

test('anyof and group negation', () => {
  const out = generate({
    rules: [
      rule({
        match: 'any',
        negate: true,
        tests: [
          { type: 'exists', fields: ['X-Spam'] },
          { type: 'header', fields: ['Subject'], match: 'contains', values: ['ad'] },
        ],
        actions: [{ type: 'keep' }],
      }),
    ],
  });
  assert.match(out, /if not anyof\(exists "X-Spam", header :contains "Subject" "ad"\)/);
});

test('nested groups produce mixed allof/anyof', () => {
  const out = generate({
    rules: [
      rule({
        name: 'Finance',
        match: 'all',
        tests: [
          { type: 'header', fields: ['Subject'], match: 'contains', values: ['statement'] },
          {
            type: 'group',
            match: 'any',
            children: [
              { type: 'address', part: 'all', fields: ['From'], match: 'is', values: ['bank@x'] },
              { type: 'address', part: 'all', fields: ['From'], match: 'is', values: ['broker@y'] },
            ],
          },
        ],
        actions: [{ type: 'keep' }],
      }),
    ],
  });
  assert.match(
    out,
    /if allof\(header :contains "Subject" "statement", anyof\(address :all :is "From" "bank@x", address :all :is "From" "broker@y"\)\)/,
  );
});

test('a single-child group collapses (no redundant allof)', () => {
  const out = generate({
    rules: [
      rule({
        tests: [{ type: 'group', match: 'all', children: [{ type: 'exists', fields: ['X-Y'] }] }],
        actions: [{ type: 'keep' }],
      }),
    ],
  });
  assert.match(out, /if exists "X-Y"\n/);
  assert.doesNotMatch(out, /allof|anyof/);
});

test('unconditional rule emits actions without an if-block', () => {
  const out = generate({ rules: [rule({ name: 'Catch-all', actions: [{ type: 'keep' }] })] });
  assert.match(out, /# rule:\[Catch-all\]\nkeep;/);
  assert.doesNotMatch(out, /\nif /);
});

test('a disabled rule is commented out but keeps its content', () => {
  const out = generate({
    rules: [
      rule({
        name: 'Off',
        enabled: false,
        tests: [{ type: 'header', fields: ['Subject'], match: 'is', values: ['x'] }],
        actions: [{ type: 'discard' }],
      }),
    ],
  });
  assert.match(out, /# rule:\[Off\] \(disabled\)/);
  assert.match(out, /# if header :is "Subject" "x"/); // content preserved as comments
  assert.match(out, /# {2}discard;|# \tdiscard;/);
  // ...but nothing runs: no uncommented code.
  assert.doesNotMatch(out, /^if /m);
  assert.doesNotMatch(out, /^\s*discard;/m);
});

test('user strings are escaped — no Sieve injection', () => {
  const out = generate({
    rules: [rule({ actions: [{ type: 'fileinto', mailbox: 'Evil"; discard; #' }] })],
  });
  // The quote is escaped and the injected `discard` stays inside the string.
  assert.match(out, /fileinto "Evil\\"; discard; #";/);
  assert.equal((out.match(/discard;/g) ?? []).length, 1);
});

test('requiredExtensions reflects exactly what is used', () => {
  const model: SieveModel = {
    rules: [
      rule({
        tests: [
          { type: 'envelope', fields: ['from'], match: 'is', values: ['a@b'] },
          { type: 'body', match: 'contains', values: ['x'] },
          { type: 'header', fields: ['X'], match: 'regex', values: ['.*'] },
          { type: 'header', fields: ['X-Count'], match: 'count', relation: 'ge', comparator: 'i;ascii-numeric', values: ['2'] },
        ],
        actions: [
          { type: 'fileinto', mailbox: 'a', create: true, copy: true },
          { type: 'addflag', flags: ['\\Seen'] },
          { type: 'vacation', reason: 'away' },
        ],
      }),
    ],
  };
  assert.deepEqual(requiredExtensions(model), [
    'body',
    'comparator-i;ascii-numeric',
    'copy',
    'envelope',
    'fileinto',
    'imap4flags',
    'mailbox',
    'regex',
    'relational',
    'vacation',
  ]);
});

test('disabled rules do not contribute requires', () => {
  const model: SieveModel = {
    rules: [rule({ enabled: false, actions: [{ type: 'vacation', reason: 'x' }] })],
  };
  assert.deepEqual(requiredExtensions(model), []);
});

test('generated scripts compile under sievec', { skip: sievecSkip }, () => {
  const model: SieveModel = {
    rules: [
      rule({
        name: 'Comprehensive',
        match: 'any',
        tests: [
          { type: 'header', fields: ['From', 'To'], match: 'contains', values: ['@example.com'] },
          { type: 'address', part: 'domain', fields: ['From'], match: 'is', values: ['spam.test'] },
          { type: 'envelope', fields: ['from'], match: 'matches', values: ['*@bad.*'] },
          { type: 'size', over: true, limit: 5_000_000 },
          { type: 'exists', fields: ['X-Spam-Flag'] },
          { type: 'body', transform: 'text', match: 'contains', values: ['lottery'] },
          { type: 'header', negate: true, fields: ['Subject'], match: 'regex', values: ['^re:'] },
          { type: 'header', fields: ['X-Priority'], match: 'value', relation: 'le', comparator: 'i;ascii-numeric', values: ['2'] },
          {
            type: 'group',
            match: 'all',
            negate: true,
            children: [
              { type: 'exists', fields: ['X-Loop'] },
              { type: 'header', fields: ['Precedence'], match: 'is', values: ['bulk'] },
            ],
          },
        ],
        actions: [
          { type: 'fileinto', mailbox: 'INBOX/Filtered', create: true, copy: true },
          { type: 'addflag', flags: ['\\Seen', '\\Flagged'] },
          { type: 'redirect', copy: true, address: 'archive@example.com' },
          { type: 'vacation', days: 7, subject: 'Away', addresses: ['me@example.com'], reason: 'On holiday\nback soon' },
          { type: 'stop' },
        ],
      }),
      rule({ id: 'r2', name: 'Catch-all', actions: [{ type: 'keep' }] }),
    ],
  };

  const result = compileSieve(generate(model));
  assert.ok(result.ok, `sievec rejected the script:\n${result.stderr}`);
});
