/**
 * Generator: rule model -> Sieve script text.
 *
 * Design goals:
 *  - Correctness: output must compile under Dovecot Pigeonhole (`sievec`).
 *  - Safety: every user string is serialised via `sieveString*`, never
 *    concatenated raw — see ../sieve/string.ts.
 *  - Round-trip: each rule carries a `# rule:[name]` metadata comment so the
 *    parser can reconstruct names and ordering losslessly.
 *  - Stability: deterministic output (sorted requires, fixed spacing) so diffs
 *    and golden tests stay meaningful.
 */

import type {
  Action,
  Comparator,
  ConditionGroup,
  ConditionNode,
  MatchType,
  RelationalOp,
  Rule,
  SieveModel,
  Test,
} from '../model/types.js';
import { sieveString, sieveStringList } from '../sieve/string.js';
import { matchKeyword, requiredExtensions } from './extensions.js';

const INDENT = '\t';
const HEADER =
  '# Generated by sieve-builder. The "# rule:[...]" comments enable round-trip\n' +
  '# editing — keep them if you edit this script by hand.';

export function generate(model: SieveModel): string {
  const blocks: string[] = [HEADER];

  const requires = requiredExtensions(model);
  if (requires.length > 0) {
    blocks.push(`require ${sieveStringList(requires)};`);
  }

  for (const rule of model.rules) {
    blocks.push(generateRule(rule));
  }

  return blocks.join('\n\n') + '\n';
}

function generateRule(rule: Rule): string {
  const marker = `# rule:[${rule.name}]`;

  if (!rule.enabled) {
    // Preserve the rule's existence (and name) without emitting live code.
    return `${marker} (disabled)`;
  }

  const body = rule.actions.map((a) => INDENT + generateAction(a)).join('\n');

  // Unconditional rule: actions run for every message, no `if` wrapper.
  if (rule.root.children.length === 0) {
    return `${marker}\n${rule.actions.map(generateAction).join('\n')}`;
  }

  return `${marker}\nif ${generateGroup(rule.root)}\n{\n${body}\n}`;
}

function generateNode(node: ConditionNode): string {
  return node.type === 'group' ? generateGroup(node) : generateTest(node);
}

/** Renders a condition group as a Sieve boolean expression, recursing on sub-groups. */
function generateGroup(group: ConditionGroup): string {
  const parts = group.children.map(generateNode);
  let expr: string;
  if (parts.length === 0) {
    // Degenerate empty group: allof() is true, anyof() is false.
    expr = group.match === 'all' ? 'true' : 'false';
  } else if (parts.length === 1) {
    // allof(x) == anyof(x) == x — collapse to keep output clean.
    expr = parts[0]!;
  } else {
    expr = `${matchKeyword(group.match)}(${parts.join(', ')})`;
  }
  return group.negate ? `not ${expr}` : expr;
}

// --- Tests ------------------------------------------------------------------

function generateTest(test: Test): string {
  const rendered = renderTest(test);
  return test.type !== 'size' && test.negate ? `not ${rendered}` : rendered;
}

function renderTest(test: Test): string {
  switch (test.type) {
    case 'header':
      return `header${matchArgs(test)} ${sieveStringList(test.fields)} ${sieveStringList(test.values)}`;
    case 'address':
      return `address${part(test.part)}${matchArgs(test)} ${sieveStringList(test.fields)} ${sieveStringList(test.values)}`;
    case 'envelope':
      return `envelope${part(test.part)}${matchArgs(test)} ${sieveStringList(test.fields)} ${sieveStringList(test.values)}`;
    case 'exists':
      return `exists ${sieveStringList(test.fields)}`;
    case 'size':
      return `size :${test.over ? 'over' : 'under'} ${String(test.limit)}`;
    case 'body': {
      const transform = renderBodyTransform(test.transform, test.contentTypes);
      return `body${transform}${matchArgs(test)} ${sieveStringList(test.values)}`;
    }
  }
}

function renderBodyTransform(
  transform: 'raw' | 'text' | 'content' | undefined,
  contentTypes: string[] | undefined,
): string {
  if (!transform) return '';
  if (transform === 'content') {
    return ` :content ${sieveStringList(contentTypes ?? [''])}`;
  }
  return ` :${transform}`;
}

/** Renders the comparator + match-type tags shared by content tests. */
function matchArgs(test: {
  match: MatchType;
  comparator?: Comparator;
  relation?: RelationalOp;
}): string {
  let out = '';
  if (test.comparator) out += ` :comparator ${sieveString(test.comparator)}`;
  switch (test.match) {
    case 'is':
    case 'contains':
    case 'matches':
    case 'regex':
      out += ` :${test.match}`;
      break;
    case 'count':
    case 'value':
      out += ` :${test.match} ${sieveString(test.relation ?? 'eq')}`;
      break;
  }
  return out;
}

function part(p: 'all' | 'localpart' | 'domain' | undefined): string {
  return p ? ` :${p}` : '';
}

// --- Actions ----------------------------------------------------------------

function generateAction(action: Action): string {
  switch (action.type) {
    case 'fileinto':
      return `fileinto${action.copy ? ' :copy' : ''}${action.create ? ' :create' : ''} ${sieveString(action.mailbox)};`;
    case 'redirect':
      return `redirect${action.copy ? ' :copy' : ''} ${sieveString(action.address)};`;
    case 'keep':
      return 'keep;';
    case 'discard':
      return 'discard;';
    case 'stop':
      return 'stop;';
    case 'setflag':
    case 'addflag':
    case 'removeflag':
      return `${action.type} ${sieveStringList(action.flags)};`;
    case 'vacation':
      return generateVacation(action);
  }
}

function generateVacation(action: Extract<Action, { type: 'vacation' }>): string {
  let out = 'vacation';
  if (action.days !== undefined) out += ` :days ${String(action.days)}`;
  if (action.subject !== undefined) out += ` :subject ${sieveString(action.subject)}`;
  if (action.from !== undefined) out += ` :from ${sieveString(action.from)}`;
  if (action.addresses && action.addresses.length > 0) {
    out += ` :addresses ${sieveStringList(action.addresses)}`;
  }
  if (action.handle !== undefined) out += ` :handle ${sieveString(action.handle)}`;
  return `${out} ${sieveString(action.reason)};`;
}
